# Generated by Django 4.1.3 on 2022-12-02 13:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoundingBox',
            fields=[
                ('pk_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('id', models.IntegerField()),
                ('xmin', models.IntegerField()),
                ('ymin', models.IntegerField()),
                ('xmax', models.IntegerField()),
                ('ymax', models.IntegerField()),
            ],
            options={
                'db_table': 'boundingbox',
            },
        ),
        migrations.CreateModel(
            name='CombinedFrame',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frame', models.IntegerField()),
                ('img_path', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'frame',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'group',
            },
        ),
        migrations.CreateModel(
            name='Keypoints',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'keypoints',
                'default_related_name': '+',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('box', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.boundingbox')),
                ('frame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people', to='api.combinedframe')),
                ('keypoints', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='api.keypoints')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('p', models.FloatField()),
            ],
            options={
                'db_table': 'point',
            },
        ),
        migrations.CreateModel(
            name='WDTeahcer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isaction', models.BooleanField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
            options={
                'db_table': 'watching_display_teacher',
            },
        ),
        migrations.CreateModel(
            name='PTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isaction', models.BooleanField()),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
            options={
                'db_table': 'programming_teacher',
            },
        ),
        migrations.AddField(
            model_name='keypoints',
            name='l_ankle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='l_bigtoe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='l_ear',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='l_elbow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='l_eye',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='l_heel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='l_hip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='l_knee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='l_shoulder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='l_smalltoe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='l_wrist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='midhip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='neck',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='nose',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='r_ankle',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='r_bigtoe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='r_ear',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='r_elbow',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='r_eye',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='r_hell',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='r_hip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='r_knee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='r_shoulder',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='r_smalltoe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='keypoints',
            name='r_wrist',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.point'),
        ),
        migrations.AddField(
            model_name='combinedframe',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='api.group'),
        ),
        migrations.AddConstraint(
            model_name='combinedframe',
            constraint=models.UniqueConstraint(fields=('frame', 'group'), name='group_frame_unique'),
        ),
    ]
