# Generated by Django 4.1.3 on 2022-12-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pteacher',
            name='isaction',
        ),
        migrations.RemoveField(
            model_name='wdteahcer',
            name='isaction',
        ),
        migrations.AddField(
            model_name='pteacher',
            name='label',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='wdteahcer',
            name='label',
            field=models.IntegerField(default=0),
        ),
    ]
