# Generated by Django 4.1.3 on 2022-12-05 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_pteacher_isaction_remove_wdteahcer_isaction_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WDTeahcer',
            new_name='WDTeacher',
        ),
        migrations.CreateModel(
            name='WTHTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.IntegerField(default=0)),
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.person')),
            ],
            options={
                'db_table': 'what_they_have_teacher',
            },
        ),
    ]
