# Generated by Django 4.1.3 on 2022-12-07 08:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_wdteahcer_wdteacher_wthteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
            options={
                'db_table': 'click',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
            options={
                'db_table': 'release',
            },
        ),
        migrations.AddField(
            model_name='combinedframe',
            name='screenshot_path',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Drag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.click')),
                ('frame', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drag', to='api.combinedframe')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drags', to='api.group')),
                ('release', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.release')),
            ],
            options={
                'db_table': 'drag',
            },
        ),
        migrations.AddConstraint(
            model_name='drag',
            constraint=models.UniqueConstraint(fields=('frame', 'group'), name='unique_drag'),
        ),
    ]
