# Generated by Django 4.1.3 on 2022-12-07 09:13

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_drag_frame_click_frame_drag_person_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='drag',
            name='unique_drag',
        ),
        migrations.AlterField(
            model_name='drag',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddConstraint(
            model_name='drag',
            constraint=models.UniqueConstraint(fields=('click', 'group', 'release'), name='unique_drag'),
        ),
    ]
