# Generated by Django 4.1.3 on 2022-12-07 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_drag_unique_drag_alter_drag_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drag',
            name='frame',
        ),
    ]
