# Generated by Django 4.1.3 on 2022-12-08 16:32

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_drag_frame'),
    ]

    operations = [
        migrations.CreateModel(
            name='MousePos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
            ],
            options={
                'db_table': 'mouse_position',
            },
        ),
        migrations.RenameModel(
            old_name='Drag',
            new_name='MouseDrag',
        ),
        migrations.RemoveField(
            model_name='combinedframe',
            name='screenshot_path',
        ),
        migrations.RenameModel(
            old_name='Click',
            new_name='MouseClick',
        ),
        migrations.RenameModel(
            old_name='Release',
            new_name='MouseRelease',
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('screenshot_path', models.CharField(max_length=100)),
                ('frame', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.combinedframe')),
                ('mouse_click', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.mouseclick')),
                ('mouse_pos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.mousepos')),
                ('mouse_release', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.mouserelease')),
            ],
            options={
                'db_table': 'device',
            },
        ),
    ]
