# Generated by Django 4.1.3 on 2022-12-19 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_teacher2_unique_teacher_alter_teacher2_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher2',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='api.person'),
        ),
    ]
