# Generated by Django 4.1.4 on 2022-12-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_teacher2_person'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher2',
            new_name='Teacher',
        ),
        migrations.RemoveField(
            model_name='wdteacher',
            name='model',
        ),
        migrations.RemoveField(
            model_name='wdteacher',
            name='person',
        ),
        migrations.RemoveField(
            model_name='wthteacher',
            name='model',
        ),
        migrations.RemoveField(
            model_name='wthteacher',
            name='person',
        ),
        migrations.DeleteModel(
            name='PTeacher',
        ),
        migrations.DeleteModel(
            name='WDTeacher',
        ),
        migrations.DeleteModel(
            name='WTHTeacher',
        ),
    ]
